import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Toaster } from "react-hot-toast";
// import { ChatWidget } from "@/components/ChatWidget";

import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Krishi Netra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ClerkLoading>
            <div className="flex items-center justify-center min-h-screen text-2xl">
              LOADING...
            </div>
          </ClerkLoading>

          <ClerkLoaded>
            <div>
              <Navbar />
              <div>{children}</div>
              <Footer />
              {/* <ChatWidget /> */}
              <Toaster position="top-center" />
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
